some fedora lovers opinions & when it is not p…
thisisamna/LDP-2024 pull request #13
Opened 2024-03-03 20:41 UTC by KenzyAdel

closes #6

2024-03-03 22:19 UTC, thisisamna requested changes
Great work again! Just add the spaces in the titles, and make sure to capitalize Fedora.

2024-03-03 22:19 UTC, thisisamna commented on Fedora/README.md
> +If you don't like changes and want a very stable distribution then fedora will not be the best choice for you.
Capital F

2024-03-03 22:19 UTC, thisisamna commented on Fedora/README.md
> +##When it might not be beneficial to use fedora?
Capital F and space

2024-03-03 22:19 UTC, thisisamna commented on Fedora/README.md
> +##Real Life use case
Space

2024-03-05 18:59 UTC, KenzyAdel commented
All is done here. Please, view changes ASAP and tell me if there is any notes

2024-03-05 19:42 UTC, thisisamna approved these changes
LGTM!

2024-03-05 19:45 UTC, merged