Arch Pros & Cons finish
thisisamna/LDP-2024 pull request #16
Opened 2024-03-04 18:15 UTC by sara-saye

closes #3

2024-03-04 21:29 UTC, thisisamna requested changes
Nice work!

2024-03-04 21:29 UTC, thisisamna commented on Arch/README.md
> +# cons
Capitalize the C

2024-03-04 21:29 UTC, thisisamna commented on Arch/README.md
> +      LINUX ARCH supports PACMAN management. This technology provides the ability to upgrade the entire system with a single pacman command - Syu. Loading of new versions of packages is performed by
Change "LINUX ARCH" to "Arch Linux" for consistency

2024-03-04 21:29 UTC, thisisamna commented on Arch/README.md
> +      your source for Arch Linux documentation on the web.
Most distros have a wiki, so this alone isn't a pro. The real pro for Arch is that its wiki is rich, detailed, and up-to-date, making it superior to any other distro's wiki . Maybe we can say something about that here!

2024-03-04 21:29 UTC, thisisamna commented on Arch/README.md
> +* **Difficult to install**
Maybe let's not make these bold, and add a bit of detail. For example: 
- Can be difficult to install and set up for the average user
- Not very usable out of the box, and requires a lot of configuration

2024-03-04 22:41 UTC, sara-saye commented
All changes have done!

2024-03-05 15:14 UTC, thisisamna approved these changes
Awesome, thank you! Merging.

2024-03-05 15:21 UTC, merged