finished fedora History
thisisamna/LDP-2024 pull request #9
Opened 2024-03-03 19:57 UTC by KenzyAdel

2024-03-03 21:00 UTC, thisisamna requested changes

2024-03-03 21:00 UTC, thisisamna commented on Fedora/README.md
> +#Fedora
Need a space here between the # and the title

2024-03-03 21:00 UTC, thisisamna commented on Fedora/README.md
> +##Distribution History
Space here too between # and title

2024-03-03 21:00 UTC, thisisamna commented on Fedora/README.md
> +Although fedora is not as stable as Red Hat Enterprise Linux (RHEL), but it is completely free to use and full of innovations, unlike Red Hat that is typically sold through an annual subscription.
Awesome work. Capitalize the f of Fedora here

2024-03-03 21:00 UTC, thisisamna commented on Fedora/README.md
> +##Distro Image
Space here too

2024-03-03 21:15 UTC, thisisamna commented on Fedora/README.md
> +##Distro Image
Note: The changes are minor and I'm not sure whether I should've merged and requested fixes later, but I'll play it safe

2024-03-05 17:58 UTC, KenzyAdel commented
Spaces and redirecting all images

2024-03-05 18:02 UTC, thisisamna approved these changes
LGTM. Thank you Kenzy!

2024-03-05 18:02 UTC, merged